services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: routePlan_app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./data:/usr/src/app/data
    environment:
      - PORT=3000
      - ORSM_URL=http://osrm:5000/route/v1/driving/
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - osrm
    command: npm run dev

  osrm:
    image: osrm/osrm-backend:v5.26.0
    container_name: osrm
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"
    command: osrm-routed /data/israel-and-palestine-latest.osrm

  redis:
    image: redis:latest
    container_name: routePlan_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
